name       : python-asn1crypto
version    : 1.5.1
release    : 11
source     :
    - https://github.com/wbond/asn1crypto/archive/refs/tags/1.5.1.tar.gz : c06e6827971891a7c42299eff3f0881d6fbf1ada53f11c5797240a9c0cec6a1c
homepage   : https://github.com/wbond/asn1crypto
license    : MIT
component  : programming.python
summary    : Python ASN.1 library with a focus on performance and a pythonic API
description: |
    Fast ASN.1 parser and serializer with definitions for private keys, public keys, certificates, CRL, OCSP, CMS, PKCS#3, PKCS#7, PKCS#8, PKCS#12, PKCS#5, X.509 and TSP.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
