name       : python-asn1crypto
version    : 1.4.0
release    : 10
source     :
    - https://github.com/wbond/asn1crypto/archive/1.4.0.tar.gz : 1aeb3e243772fdbf815867b41320436b86f05a6aa14265d90910da780910f39d
license    : MIT
component  : programming.python
summary    : Python ASN.1 library with a focus on performance and a pythonic API
description: |
    A fast, pure Python library for parsing and serializing ASN.1 structures.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
