name       : python-asn1crypto
version    : 1.2.0
release    : 6
source     :
    - https://github.com/wbond/asn1crypto/archive/1.2.0.tar.gz : 9d8ac276bdeb5551313580fb4c8c50d50e2faac6862f5916802ae65c8b187468
license    : MIT
component  : programming.python
summary    : Python ASN.1 library with a focus on performance and a pythonic API
description: |
    A fast, pure Python library for parsing and serializing ASN.1 structures.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
