name       : python-asn1crypto
version    : 0.22.0
release    : 1
source     :
    - https://github.com/wbond/asn1crypto/archive/0.22.0.tar.gz : e0b36be480a1aef9290250053e880e2860203c4d2c284a63b57350931008c9ce
license    : MIT
component  : programming.python
summary    : Python ASN.1 library with a focus on performance and a pythonic API
description: |
    A fast, pure Python library for parsing and serializing ASN.1 structures.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
