name       : python-asn1crypto
version    : 0.24.0
release    : 4
source     :
    - https://github.com/wbond/asn1crypto/archive/0.24.0.tar.gz : d2a82bb3c29e1abcb376b59679510b58dd796c813f8983f2db9b45e9ab228190
license    : MIT
component  : programming.python
summary    : Python ASN.1 library with a focus on performance and a pythonic API
description: |
    A fast, pure Python library for parsing and serializing ASN.1 structures.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
