name       : python-asn1crypto
version    : 0.23.0
release    : 2
source     :
    - https://github.com/wbond/asn1crypto/archive/0.23.0.tar.gz : 884b5ba3d9b442c1729f67981d3ddeb85a1d7dbd35199000a0bc8d077548352d
license    : MIT
component  : programming.python
summary    : Python ASN.1 library with a focus on performance and a pythonic API
description: |
    A fast, pure Python library for parsing and serializing ASN.1 structures.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python run.py tests
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 run.py tests
    popd
